[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
itertools = "0.10"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "01"
path = "src/01.rs"

[[bin]]
name = "02"
path = "src/02.rs"

[[bin]]
name = "03"
path = "src/03.rs"
